version: "2"
services:
  app:
    build: .
    ports:
    - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
  db:
    build: db/.
    volumes:
    - ./temp/db:/data/db
    ports:
    - "27017:27017"

